// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUZrGzNdUlvyJ_FVR5SLiYCmUPljCEYXQ',
    appId: '1:11928705272:web:4277f42aa039967db8430d',
    messagingSenderId: '11928705272',
    projectId: 'today-meet-2',
    authDomain: 'today-meet-2.firebaseapp.com',
    storageBucket: 'today-meet-2.appspot.com',
    measurementId: 'G-B2XVR7RV29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu7x44ySaVMZZkP29OziE6FBgYpQ8wtyY',
    appId: '1:11928705272:android:08163ba8cbdf8237b8430d',
    messagingSenderId: '11928705272',
    projectId: 'today-meet-2',
    storageBucket: 'today-meet-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn7wA2PFZeaic4vlXHcQunk995vP_bm9s',
    appId: '1:11928705272:ios:21e89212129dd71ab8430d',
    messagingSenderId: '11928705272',
    projectId: 'today-meet-2',
    storageBucket: 'today-meet-2.appspot.com',
    androidClientId: '11928705272-93p6jpjanmameslpveujufllmngs3icn.apps.googleusercontent.com',
    iosClientId: '11928705272-chv6pd09424tb0p7nqk77m8csh22gocm.apps.googleusercontent.com',
    iosBundleId: 'com.example.front',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn7wA2PFZeaic4vlXHcQunk995vP_bm9s',
    appId: '1:11928705272:ios:21e89212129dd71ab8430d',
    messagingSenderId: '11928705272',
    projectId: 'today-meet-2',
    storageBucket: 'today-meet-2.appspot.com',
    androidClientId: '11928705272-93p6jpjanmameslpveujufllmngs3icn.apps.googleusercontent.com',
    iosClientId: '11928705272-chv6pd09424tb0p7nqk77m8csh22gocm.apps.googleusercontent.com',
    iosBundleId: 'com.example.front',
  );
}
